### ISSUE TITLE
1.18.2 update support, pls

### ISSUE THREAD

**Issue by Ja5pberry** [Siphalor/nbt-crafting#101]
Pls get 1.18.2 support! <3

**Comment by Siphalor** [comment]
There are already versions for 1.18.2. In fact, I'm thinking about dropping 1.18.1 support. 

I guess you came from CurseForge, which shows the 1.18.1 version on the right. I can't do anything about that. 
If you want to download the 1.18.2 version, you can use the "Files" tab.
