### ISSUE TITLE
game fails to load worlds with a "buffer length is less than zero" error

### ISSUE THREAD

**Issue by Finlye** [Siphalor/nbt-crafting#103]
version 1.18.2

game fails to load generated worlds and outputs the error:
io.netty.handler.codec.DecoderException: The received encoded string buffer length is less than zero! Weird string!

I have attached the rei associated with this. the error occurs upon loading nbt advanced recipies.
Note: I am not sure on if this is a incompatability issue or not
[nbt crash.log](https://github.com/Siphalor/nbt-crafting/files/8884548/nbt.crash.log)

**Comment by Siphalor** [comment]
That has apparently been a known issue in TropheusJ's library "serialization-hooks".

Talking to the author revealed, that it has since been fixed and pushed out.
Please check all of TropheusJ's mods in your pack and update them to the latest version :smiley:
