### ISSUE TITLE
 nbt crafting advanced recipe packet that is too big

### ISSUE THREAD

**Issue by TheButterbrotMan** [Siphalor/nbt-crafting#107]
https://bytebin.lucko.me/5Y1sDTcwqS

**Comment by TheButterbrotMan** [comment]
https://github.com/FabricMC/fabric/issues/2342

**Comment by Sunconure11** [comment]
Anything new here? No new fabric builds have popped up.

**Comment by TheButterbrotMan** [comment]
Saphilor has uploaded a version here to test: https://cdn.discordapp.com/attachments/989915187899432981/992704513427382283/nbtcrafting-2.1.4-alpha.1mc1.18.2.jar

But i didnt had time yet to do so.

**Comment by Sunconure11** [comment]
Will have to test when another issue gets cleared up

**Comment by Siphalor** [comment]
I think I'm gonna release it as a public alpha now.
I planned to do that earlier this week but didn't have time for it.

@Sunconure11, what's currently the showstopper for you?

**Comment by Sunconure11** [comment]
Overweight farming, but I’ve decided to move to 1.19

**Comment by Siphalor** [comment]
Since the startup crash with beta 2 is now resolved, I'd like to get some feedback if beta 3 actually fixes this :slightly_smiling_face:

**Comment by Sunconure11** [comment]
You'll have to wait. I moved to 1.19 and I'm busy debugging my modpack. In addition, I am also dealing with having a pretty big upgrade done to my PC.
