### ISSUE TITLE
[bug] Crash at start of client

### ISSUE THREAD

**Issue by TheButterbrotMan** [Siphalor/nbt-crafting#112]
**Version**
1.18.2 & nbtcrafting-2.1.4-beta.2+mc1.18.2
**Describe the bug**
Crashing at start of client

**To Reproduce**
1. Download https://www.curseforge.com/minecraft/modpacks/deathdusk
2. Update nbtcrafting

**Expected behavior**
Do not crash.

**Log**
https://bytebin.lucko.me/883TSFhzGM

**Comment by Sheep7798** [comment]
I have the same problem but with other mods

**Comment by Siphalor** [comment]
Should be fixed in 2.1.4-beta.3
