### ISSUE TITLE
[bug] example title

### ISSUE THREAD

**Issue by Ssobeck** [Siphalor/nbt-crafting#113]
**Version**
1.19
**Describe the bug**
It says entry point is deprecated in rei 
![scrn](https://user-images.githubusercontent.com/109638002/179877036-8d25eb22-ab18-42a8-9788-55e620e74d6f.png)

**To Reproduce**
1. opening game

**Comment by Siphalor** [comment]
Hi, thanks for reporting this :)
This has already been recorded and is tracked as #108.
A fix is implemented in 2.1.4-beta.2.

That version is unfortunately broken right now, I plan to release a working beta version today though.
