### ISSUE TITLE
Maven link not responding?

### ISSUE THREAD

**Issue by LIUKRAST** [Siphalor/nbt-crafting#116]
Yeah, title explains
could not get https://maven.siphalor.de/de/siphalor/nbtcrafting-1.19/maven-metadata.xml

**Comment by Siphalor** [comment]
The server had some planned maintenance earlier today and since then hasn't been reachable.
I filed a support ticket, but as I am extremely busy right now I can't really do anything more right now.

I'll try to report back when the issue is resolved.

**Comment by amot-dev** [comment]
Looks like it's back up again

**Comment by Siphalor** [comment]
Indeed it is :+1:
