### ISSUE TITLE
[bug] Dupe on bundles

### ISSUE THREAD

**Issue by cbejl** [Siphalor/nbt-crafting#119]
**Version**
Minecraft 1.19.2 mod v2.1.4 
**Describe the bug**
if remove the contents of the bundle during crafting - the result of crafting will remain with the NBT tag of the extracted resources
[(bug video)](https://drive.google.com/file/d/1o5bRr5TrWXwm7n_Us7cgYuUZZRh4ZJdl/view?usp=sharing)

**To Reproduce**
1. I'm making a mod to the colored bundle and use $ for copy NBT with bundle content.
2. Dupe

**Expected behavior**
I expected that the NBT of the result would also change to empty

**Log**
-

**Additional context**
in iingredients just bundle and red dye, in result:
"item": "coloredbundel:red_bundel",
    "data": {
      "$": "i0"
    }

**Comment by Siphalor** [comment]
That's actually a fun little oversight in the vanilla code that probably just hasn't popped up, since they're not doing crafting with bundles yet ^^
