### ISSUE TITLE
Shaped recipe not working

### ISSUE THREAD

**Issue by MrIbby** [Siphalor/nbt-crafting#12]
**Version**
(Dev environment)
Minecraft Version: 1.14.2
NBT Crafting Version: 1.1.15+1.14.1

**Describe the bug**
Discussed in Discord (I could describe here if you want)

**To Reproduce**
1. Clone https://github.com/MrIbby/shulker-bag
2. Set up workspace
3. Run client
4. Attempt to craft Shulker Bag as follows:

```
###
#X#
###
```

`#` is leather and `X` is a shulker box.

**Expected behavior**
The recipe should output a shulker bag that has the same NBT as the inputted shulker box.

**Log**
https://gist.github.com/MrIbby/1026bba27f8a6036d842505445b8fb34

**Additional context**
Dev environment

**Comment by Siphalor** [comment]
your recipe should work now ;)
