### ISSUE TITLE
[bug] REI is depricating an entry point.

### ISSUE THREAD

**Issue by netcore10** [Siphalor/nbt-crafting#125]
**Version**
1.19.2

**Describe the bug**
Just an REI warning.

**Additional context**
![image](https://user-images.githubusercontent.com/181536/201431915-1a176c1c-3db1-4839-b4d1-bc0578dd10b8.png)

i cant seem to find a way to hide the warning.

**Comment by Siphalor** [comment]
That should be fixed since at least 2.1.4.
Please update to the latest version and try again :)

**Comment by netcore10** [comment]
oh i guess, a mod pulled internally without using it as a dependency. found out when i do add it, i end up crashing for some reason. https://paste.atlauncher.com/view/71bb0d8a-b8f5-454e-bebd-8e816bf863ba

**Comment by netcore10** [comment]
I can't find the mod using it for the life of me though

**Comment by Siphalor** [comment]
I think you accidentally downloaded the alpha version of this mod.
The alphas for version 3.0 are still pretty unstable and don't work well with the stable releases.

If you download a stable release, e.g. version 2.2.2, you should be good to go :)

**Comment by netcore10** [comment]
Oh! that's better. Sorry for all the trouble.
