### ISSUE TITLE
Feature Request: NBT in Stonecutter recipes' result

### ISSUE THREAD

**Issue by PhantomDoom741** [Siphalor/nbt-crafting#15]
Hey there, today I was working on my datapack and I've noticed that stonecutter recipes can't give an item with one or more NBT tags in their result. Here's the JSON I wrote for my recipe.
```json
{
    "type": "minecraft:stonecutting",
    "ingredient": {
        "item": "minecraft:iron_ore"
    },
    "result": "minecraft:turtle_egg",
    "data": "{CustomModelData:1}",
    "count": 2
}
```

**Comment by Siphalor** [comment]
This is fixed in the 1.15-2.0 branch. 
Either check out the alpha versions or wait until it gets more stable 😉.
