### ISSUE TITLE
Crash in client connected to "Open to LAN" game

### ISSUE THREAD

**Issue by calloatti** [Siphalor/nbt-crafting#17]
**Version**
1.14.3 Fabric
nbtcrafting-1.2.1+1.14.3-pre2.jar

**Describe the bug**
When playing connected to an "Open to LAN" game, when trying to place a bottle in the brewing stand the game crashes.

**To Reproduce**
1. Start a game and open it to lan
2. Connect to said game from another PC
3. Open the brewing stand GUI and try to place a bottle
4. Game crashes

**Expected behavior**
The game does not crash.

**Log**
https://paste.ee/p/UGf0c

**Additional context**

When doing the exact same thing but in the PC hosting the "Open to LAN" game, the game does not crash.

> looks like either the MinecraftClient instance or server thing is null https://github.com/Siphalor/nbt-crafting/blob/master/src/main/java/de/siphalor/nbtcrafting/client/ClientCore.java#L23
(coderbot)

**Comment by Siphalor** [comment]
I feared that 😨
