### ISSUE TITLE
Unknown type in dollar expression

### ISSUE THREAD

**Issue by Boundarybreaker** [Siphalor/nbt-crafting#21]
**Version**
Minecraft 1.14.4, NBT Crafting 1.2.1
**Describe the bug**
I'm getting a DollarException when trying to use dollars in an output for a recipe. My goal is to copy tags from inputs to the output, but it's throwing a `DollarException: Unknown type in dollar expression` whenever I try to craft it. It could either be because the tags I'm trying to carry over strings to the result or because I grab tags from multiple inputs.

**To Reproduce**
1. Use [this json](https://github.com/CottonMC/Workshop/blob/master/src/main/resources/data/workshop/recipes/wood_pickaxe_with_grass_rope.json) (uses items from Workshop, but should work with any items with the same tags)
2. When the recipe is put together in a crafting bench, the exception is thrown

**Expected behavior**
The output item should have the tags `{Binding:"string",HeadBinding:<the value of Binding on the head item>,HandleBinding:<the value of Binding on the handle item}`

**Log**
[exception](https://gist.github.com/Boundarybreaker/71cd7cafcc9dff608243a8f9412cd6c5)

**Additional context**
When attempted, the head and handle each have NBT tags of exactly either `{Binding:"vine"}`, `{Binding:"silk"}`, or `{}`.

**Comment by Siphalor** [comment]
It throws that exception when `Binding` does not exist.
I'm gonna fix it though ;)
