### ISSUE TITLE
[bug] mod crashes on latest snapshot.

### ISSUE THREAD

**Issue by Blamudia** [Siphalor/nbt-crafting#23]
**Version**
19w46b - 1.2.5-19w41a

**Describe the bug**
The 1.2.4 version goes up to 19w41a and the supposed 1.2.5 version would go from said snapshot up. But it seems that the latest snapshot is not working with this mod. everything runs smoothly but the server crashes on load if the mod installed.

**To Reproduce**
1. Fabric server 19w46b.
2. Bug appears on load.

**Expected behavior**
Server load.

**Log**
[Server.log](https://github.com/Siphalor/nbt-crafting/files/3871917/latest.log)

**Comment by Yoghurt4C** [comment]
1.15pre says hello https://pastebin.com/Q6X4zmQp

**Comment by Siphalor** [comment]
Closed thanks to Draylar :)
