### ISSUE TITLE
Feature Request: fuzzy NBT match

### ISSUE THREAD

**Issue by LemmaEOF** [Siphalor/nbt-crafting#25]
Currently, NBT matching only works with exact matches. The NBT on the stack needs to be exactly the same as the NBT in the recipe. It'd be good to have a fuzzy mode, where the NBT on the stack may have more NBT, as long as it also has all the tags and values that the recipe requires.

**Comment by Yoghurt4C** [comment]
didn't read but he's right

**Comment by Siphalor** [comment]
Matching is currently always fuzzy 🤔

**Comment by LemmaEOF** [comment]
Huh. I'll let yog know.
