### ISSUE TITLE
Easier Coding (Suggestion)

### ISSUE THREAD

**Issue by aqualxx** [Siphalor/nbt-crafting#27]
If its possible, can you please make it so you dont have to do things like putting quotation marks or maybe even the backslashes around the data part of the result code, for e.g

`"Name": {"text":"Emerald Sword","color":"dark_green","italic":false}`
instead of
`"Name": "{\"text\":\"Emerald Sword\",\"color\":\"dark_green\",\"italic\":false}"`?

This would make coding it much easier to write and learn and you wont have to change endless things.

**Comment by Nathan22211** [comment]
i think this is a limitation with JSON itself and recipes usually don't work with JSON5

**Comment by Siphalor** [comment]
It's due to how Minecraft handles text data. I have something in mind though

**Comment by Siphalor** [comment]
Will come in 2.0.0 as:
```json
"Name": {"text":"Emerald Sword","color":"dark_green","italic":false,"$stringify":true}
```
