### ISSUE TITLE
[bug] REI "+" button can't handle normal recipes

### ISSUE THREAD

**Issue by vhd** [Siphalor/nbt-crafting#29]
**Version**
Minecraft 1.15.1
RoughlyEnoughItems-3.3.5
nbtcrafting-1.2.10-rc.0+1.15.1
fabric-api-0.4.25+build.282-1.15

**Describe the bug**
After installing Nbt Crafting REI autocraft button isn't working with any recipes.
Originally found by including Linked Storage mod (which includes NBT crafting) into custom modpack

**To Reproduce**
Start fresh world and try to craft any recipe with REI "+" button

**Comment by Siphalor** [comment]
Fixed in version 2.0.
(It's an ugly fix by patching REI's code but it works)

**Comment by vhd** [comment]
Wow! That looks terribly wrong :D
Broken vanilla functions like "Registry.ITEM.getRawId" is what I'm least expecting :(
