### ISSUE TITLE
[bug] NBT Ingredients from a server's recipe don't show up in vanilla recipe book

### ISSUE THREAD

**Issue by DuncanRuns** [Siphalor/nbt-crafting#30]
Version:
1.15.1 Vanilla
NBT Crafting 1.2.10-rc.0 on Fabric Server

The bug:
Ingredients that require specific nbt (such as an enchanted book with mending) will not show up in the recipe book in any way.

To reproduce:
Use a recipe with nbt ingredients (such as the one below) on a server and a vanilla client to connect. Having all the ingredients in your inventory will correctly auto-fill, however without all the ingredients, it will only suggest the ingredients that do not have nbt. (The recipe requires a bow, a nether star, a mending book, and an infinity book)
`{
    "type": "minecraft:crafting_shapeless",
    "ingredients": [
        {
            "item": "minecraft:nether_star"
        },
        {
            "item": "minecraft:bow"
        },
		{
			"item": "minecraft:enchanted_book",
			"data":{
				"require":{
					"StoredEnchantments":[
						{"lvl":1,"id":"minecraft:mending"}
					]
				}
			}
		},
		{
			"item": "minecraft:enchanted_book",
			"data":{
				"require":{
					"StoredEnchantments":[
						{"lvl":1,"id":"minecraft:infinity"}
					]
				}
			}
		}
    ],
	"result": {
		"item": "minecraft:bow",
		"data": {
			"display": {
				"Name": "{\"text\":\"Star Bow\",\"color\":\"light_purple\",\"italic\":false}",
				"Lore":[
					"{\"text\":\"Floaty Arrows\",\"color\":\"gray\",\"bold\":false,\"italic\":false}",
					"{\"text\":\"Infinity AND Mending\",\"color\":\"gray\",\"bold\":false,\"italic\":false}",
					"{\"text\":\"Power V\",\"color\":\"gray\",\"bold\":false,\"italic\":false}",
					"{\"text\":\"Punch II\",\"color\":\"gray\",\"bold\":false,\"italic\":false}",
					"{\"text\":\"Unbreaking III\",\"color\":\"gray\",\"bold\":false,\"italic\":false}"
				]
			},
			"CustomModelData":1,
			"Enchantments":[
				{"id":"minecraft:unbreaking","lvl":3},
				{"id":"minecraft:power","lvl":5},
				{"id":"minecraft:punch","lvl":2},
				{"id":"minecraft:infinity","lvl":2},
				{"id":"minecraft:mending","lvl":1}
			],
			"HideFlags":1
		}
	}
}`
![1](https://user-images.githubusercontent.com/59705125/72098471-e8f4fc80-32f4-11ea-8d74-719d90db7396.png)
![2](https://user-images.githubusercontent.com/59705125/72098472-e8f4fc80-32f4-11ea-80c7-e135c328a815.png)

Expected behavior:
For the recipe preview to show all ingredients that are missing.
I'm expecting this not to be a bug related to the mod, as I'm guessing vanilla doesn't support NBT-tagged items in the previews, however it would be nice if possible to get vanilla to show the items without their nbt.

**Comment by Siphalor** [comment]
You're right and it worked before but it seems like 1.15 changed some of that stuff (again).

The stacks will now get previewed again (**without nbt of course**)

Thanks for reporting ;)
