### ISSUE TITLE
Crash When cut Slab Facade(Smiple pipes)

### ISSUE THREAD

**Issue by 1a2s3d4f1** [Siphalor/nbt-crafting#31]
Minecraft:1.15.1
SimplePipes:0.3.3
Nbt Crafting:1.2.11+1.15.1

**To Reproduce**
Use Stonecutter make Slab Facade 

**Expected behavior**
The game does not crash 
Can use Stonecutter to make Slab Facade

**Log**
Crash Report:https://paste.dimdev.org/dawademiye.mccrash
Error log:https://paste.dimdev.org/avokenaweh.sql

**Additional context**
[Simple pipes](https://www.curseforge.com/minecraft/mc-mods/simplepipes)

**Comment by Siphalor** [comment]
This will get fixed in 2.0.0 as the fix breaks backwards compatibility
