### ISSUE TITLE
[bug] Vanilla recipe book doesn't show nbt-tagged ingredients after reload

### ISSUE THREAD

**Issue by DuncanRuns** [Siphalor/nbt-crafting#32]
Version: 1.15.1, vanilla client on a server with NBT Crafting 1.2.11

Issue:
Exact same issue as #30, which was fixed, however the issue comes back once using a /reload.
The issue does not continue through a server restart.

To reproduce:
Use any recipe with nbt-tagged ingredients and use the command /reload. The nbt-tagged ingredients will be missing.

Expected behavior:
After reloading, the nbt-tagged items should show up as an item without nbt rather than no item at all.

**Comment by Siphalor** [comment]
That's really strange 🤔 
Fixing it this time will probably take a little longer.

**Comment by Siphalor** [comment]
This **might** be gone in the latest alpha release.
Can you check that out, please?

**Comment by DuncanRuns** [comment]
Just tried on a 1.15.1 server, and it is fixed for that.
I imagine it won't make a difference updating my server to 1.15.2 but I'm about to do that anyway so I'll let you know if it works on that as well.

**Comment by DuncanRuns** [comment]
It does work on a 1.15.2 server too.

**Comment by Siphalor** [comment]
Then I'll consider this as fixed 😉 
Thanks for bringing it up.
