### ISSUE TITLE
[bug] NullPointerException if `Core.lastServerPlayerEntity` is null

### ISSUE THREAD

**Issue by LemmaEOF** [Siphalor/nbt-crafting#34]
**Version**
Minecraft 1.15
**Describe the bug**
If `Core.hasClientMod` is called before `Core.lastServerPlayerEntity` is set, then an NPE will be thrown. `Core.hasClientMod` can be called before the server's presence packet is received and processed, causing this crash.

**To Reproduce**
1. Call `Core.hasClientMod` (called in NBT Crafting's hooks for caching matching stacks)
2. NPE is thrown

**Expected behavior**
A null-check should be done which returns false by default if NBT crafting isn't present

**Log**
https://gist.github.com/Boundarybreaker/d8eb042e76076464773d0ba3dd20053d

**Additional context**
Occurred when trying out a new compat method for LibCD and NBT Crafting

**Comment by Siphalor** [comment]
Good and helpful description. Will be fixed fast.
Still a duplicate to #33 (That title is really misleading - not your fault :) )
