### ISSUE TITLE
This mod doesn't work as it said in the description Server-side only

### ISSUE THREAD

**Issue by Neubulae** [Siphalor/nbt-crafting#38]
While joining with a vanilla client it rejects the connection and says there are registry issues.

**Comment by Siphalor** [comment]
Which version of NBTC and Minecraft are you using?

**Comment by Neubulae** [comment]
> Which version of NBTC and Minecraft are you using?

2.0.0-alpha.12, vanilla 1.15.2

**Comment by Siphalor** [comment]
Can you post the log of the server please?

**Comment by sjackser** [comment]
> Can you post the log of the server please?

https://pastebin.com/w8heRhrb

**Comment by Neubulae** [comment]
Sorry, wrong log. I can't find the log anymore, maybe I will try again later

**Comment by Neubulae** [comment]
![image](https://user-images.githubusercontent.com/24774842/74764097-020da780-52bc-11ea-99e7-86b1f33e92be.png)
https://pastebin.com/vMFHACzw

**Comment by Siphalor** [comment]
Just to document it: FabricMC/fabric#509

**Comment by Neubulae** [comment]
Should I close this issue? I incorrectly assumed that this problem persists for Vanilla Minecraft since I didn't install anything that's required client-side. I tried connecting with a slightly modified Fabric client. After I tried connecting with the _real_ vanilla client the problem seems to be on the Fabric's side, Vanilla is fine.

**Comment by Siphalor** [comment]
Since it's one of Fabric's official libraries causing the issue I still consider this a bug of Nbt Crafting. 

Also other people can see then that there's already an issue concerning this 😃

**Comment by Neubulae** [comment]
> Since it's one of Fabric's official libraries causing the issue I still consider this a bug of Nbt Crafting.
> 
> Also other people can see then that there's already an issue concerning this 😃

Ah, Ok.

**Comment by nycki93** [comment]
So, if I understand this correctly: The mod is needed on the client-side, but only if the client is already modded? That's a bit obnoxious but understandable.

**Comment by Neubulae** [comment]
> So, if I understand this correctly: The mod is needed on the client-side, but only if the client is already modded? That's a bit obnoxious but understandable.

yep

**Comment by Siphalor** [comment]
No,
This issue is resolved that means you **don't need Nbt Crafting on the client** (even if it's modded).

**Comment by Neubulae** [comment]
> No,
> This issue is resolved that means you **don't need Nbt Crafting on the client** (even if it's modded).

oof ok xD I didn't realize that

**Comment by Siphalor** [comment]
This actually has a hiccup - I will publish an update later today

**Comment by Neubulae** [comment]
> This actually has a hiccup - I will publish an update later today

What does it mean?
