### ISSUE TITLE
Unable to submit some nbt tags

### ISSUE THREAD

**Issue by Blamudia** [Siphalor/nbt-crafting#4]
Some NBT tags like SkullOwner is not being picked up on. After output the assigned item only uses NAME nbt tag and not skullowner

Example:

        "data": {
            "display": {
                "Name": "nametaginput",
                "SkullOwner": "skulltaginput" This is not being used at all! item returns with 1 nbt tag.
            }

**Comment by Siphalor** [comment]
This happens for this tag since Minecraft directly parses and writes the `display` object. Additional properties get discarded. 
You can attach own properties to most other objects but not that one ;)

By the way if you want to give a skull a player nbt data the format looks like this:
```json
		"data": {
			"display": {
				"Name": "nametaginput"
			},
			"SkullOwner": "Siphalor"
		}
```
