### ISSUE TITLE
[bug]Recipes could only be crafted once

### ISSUE THREAD

**Issue by Neubulae** [Siphalor/nbt-crafting#43]
**Version**
1.15.2 alpha.17
**Describe the bug**
After crafting for once, the recipe becomes a recipe for air, and you could no longer craft it. 
**To Reproduce**
1. Craft anything, for example a torch.
2. Boom, you crafted a torch, and the recipe disappears, and you can no longer craft torches.

**Expected behavior**
What should I expect is quite obvious right?

**Log**
No log happened.

**Additional context**
If datapacks that involves NBT crafting is required maybe create a dummy one would work? Or I'd provide mine.

**Comment by Siphalor** [comment]
done - the CurseForge release is on it's way ;)
