### ISSUE TITLE
Crash when entering in world

### ISSUE THREAD

**Issue by ghost** [Siphalor/nbt-crafting#48]
**Version**
MC Version: Snapshot 20w17a (1.16)
Fabric API: 0.7.0+build.330-1.16
Fabric Loader: 0.8.2+build.194

**Describe the bug**
Minecraft crashes after I load my the world
There's only these 3 mods :
- My own mod
- Fabric API
- NBT Crafting

**To Reproduce**
1. import NBT Crafting
2. load a world

**Expected behavior**
My world should load.

**Log**

[15:52:45] [Server thread/ERROR] (Minecraft) Exception stopping the server
 java.lang.NoSuchMethodError: de.siphalor.nbtcrafting.advancement.StatChangedCriterion.method_22510(Lnet/minecraft/server/network/ServerPlayerEntity;Ljava/util/function/Predicate;)V

Full logs here: https://pastebin.com/0inNgKX1

**Comment by Siphalor** [comment]
"Fixed" as the latest version of nbtc already runs on 20w18a ;)
