### ISSUE TITLE
[suggestion] add the possibility for a random recipe output via a loot table

### ISSUE THREAD

**Issue by Nathan22211** [Siphalor/nbt-crafting#49]

**Comment by Siphalor** [comment]
I thought about this already when this was brought first up to me.

But if you think about it you'll notice that this doesn't make a lot of sense:
* There's usually only one output slot in vanilla Minecraft. Loot tables produce multiple stacks
* Recipe books need to know an exact output stack or at least item.
* What would happen if you shift click a recipe to get a whole stack.
* Furnace/brewing recipes work passively couldn't store these items anywhere.
* Loot tables usually need a player context that recipes don't have for good reasons.
