### ISSUE TITLE
string for custom model data dosen't load in

### ISSUE THREAD

**Issue by jayjay2495** [Siphalor/nbt-crafting#50]
nbtcrafting-2.0.0-alpha.30+mc1.15.2
I'm trying to add custom crafting with the output being a minecraft:stick with CustomModelData:1 the problem being that I get the stick with the CustomModelData but when I look at the entity data of myself the stick's CustomModelData is 1b and not just 1

**To Reproduce**
1. I'm using a custom recipe .json file the contents are below
{
  "type": "minecraft:crafting_shaped",
  "group": "sticks",
  "pattern": [
    "#",
    "#"
  ],
  "key": {
    "#": {
      "item": "minecraft:birch_planks"
    }
  },
  "result": {
    "item": "minecraft:stick",
	"data": {
    "CustomModelData": 1
  },
    "count": 4
  }
} 
2. when going into game I can craft the item and the tool tips show there is nbt data but using /data get entity command on myself shows that the items CustomModelData is 1b

**Expected behavior**
I expect to get an item with {CustomModelData: 1} instead I get {CustomModelData: 1b}

**Log**
The important parts of the log.

**Additional context**
If I'm actual doing something wrong, If someone could put the correct way of doing it would be very much appreciated.

**Comment by jayjay2495** [comment]
so apparently the CustomModelData work exactly the same even with the naming being 1b instead of 1

**Comment by Felix14-v2** [comment]
@jayjay2495 , have you found a solution for this?
