### ISSUE TITLE
[bug] Server crash when placing item in crafting table

### ISSUE THREAD

**Issue by throwoutyourgoldteeth** [Siphalor/nbt-crafting#52]
**Version**
[Server] Minecraft 1.16.2-pre1, Fabric 0.9.0-build 204, Fabric API 0.16.3-build 390, REI 5.0.2*, NBT Crafting 2.0.0-beta1.
[Client] Minecraft 1.16.2-pre1 unmodded.
_*I've also tested it with REI 5.0.0 and no REI installed at all, to similar effect._
**Describe the bug**
Placing an item into the crafting table or inventory crafting UI, regardless of whether or not it would actually result in a valid recipe, immediately crashes the server and disconnects the client with a generic "Server closed" message. This only seems to occur with crafting GUIs, and does not seem to affect furnaces, smithing tables, brewing stands, or stonecutters. 
The same crash occurs when clicking an entry in the recipe book UI in crafting tables or furnaces, again regardless of whether or not materials are available for the recipe.

**To Reproduce**
Install the server with the aforementioned parameters and place an item in a crafting table.

**Expected behavior**
The server doesn't crash when an item goes into the crafting table.

**Log**
> Description: Exception in server tick loop
> java.lang.NoSuchMethodError: net.minecraft.class_2348.method_10249(Ljava/lang/Object;)I
> 	at net.minecraft.class_1662.getStackPair(class_1662.java:536)
> 	at net.minecraft.class_1662.method_7408(class_1662.java:564)
> 	at net.minecraft.class_1662.method_20478(class_1662.java:37)
> 	at net.minecraft.class_1867.method_17730(class_1867.java:62)
> 	at net.minecraft.class_1867.method_8115(class_1867.java:15)
> 	at net.minecraft.class_3956.method_17725(class_3956.java:30)
> 	at net.minecraft.class_1863.method_17718(class_1863.java:70)
> 	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
> 	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
> 	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.tryAdvance(CollectSpliterators.java:60)
> 	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
> 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
> 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> 	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
> 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> 	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
> 	at net.minecraft.class_1863.method_8132(class_1863.java:70)
> 	at net.minecraft.class_1714.method_17399(class_1714.java:66)
> 	at net.minecraft.class_1714.method_17401(class_1714.java:80)
> 	at net.minecraft.class_3914.method_17394(class_3914.java:35)
> 	at net.minecraft.class_3914$2.method_17395(class_3914.java:22)
> 	at net.minecraft.class_3914.method_17393(class_3914.java:34)
> 	at net.minecraft.class_1714.method_7609(class_1714.java:80)
> 	at net.minecraft.class_1715.method_5447(class_1715.java:70)
> 	at net.minecraft.class_1735.method_7673(class_1735.java:82)
> 	at net.minecraft.class_1703.method_30010(class_1703.java:375)
> 	at net.minecraft.class_1703.method_7593(class_1703.java:177)
> 	at net.minecraft.class_3244.method_12076(class_3244.java:1292)
> 	at net.minecraft.class_2813.method_12191(class_2813.java:32)
> 	at net.minecraft.class_2813.method_11054(class_2813.java:10)
> 	at net.minecraft.class_2600.method_11072(class_2600.java:21)
> 	at net.minecraft.class_3738.run(class_3738.java:18)
> 	at net.minecraft.class_1255.method_18859(class_1255.java:144)
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
> 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:762)
> 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:153)
> 	at net.minecraft.class_1255.method_16075(class_1255.java:118)
> 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:744)
> 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:738)
> 	at net.minecraft.class_1255.method_5383(class_1255.java:103)
> 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:255)
> 	at java.lang.Thread.run(Unknown Source)

**Additional context**
This occurs regardless of whether or not the world has any datapacks loaded.
It's also remotely possible that I have no idea what I'm doing and have in fact just installed everything wrong. Just started using Fabric yesterday. Though, for whatever it's worth, this doesn't seem to happen in 1.16.1.

**Comment by Siphalor** [comment]
I think I fixed that in Beta 2 without referencing this issue :)
