### ISSUE TITLE
REI recipe auto-insertion broken

### ISSUE THREAD

**Issue by Aphyxia** [Siphalor/nbt-crafting#53]
Roughly Enough Items recipe auto-insertion (+) button is broken and always say not enough materials with this mod installed. Tried with only these two mods and default configs.

Versions:
This mod [1.16.x] 1.2.4
MC 1.16.1
REI [Fabric 1.16.x] v4.11.0
Fabric 0.9.1 build 205

**Comment by Siphalor** [comment]
This should be fixed thanks to a fix on REI's side :)
