### ISSUE TITLE
[bug] MixinItemStack breaks cardinal components

### ISSUE THREAD

**Issue by Frontrider** [Siphalor/nbt-crafting#59]
**Version**
1.6.4
**Describe the bug**
This inject is extremely invasive and specifically breaks cardinal components and everyone else who is trying to do anything with items.
https://github.com/Siphalor/nbt-crafting/blob/5d7a45a0d6cc6956742f90f89b9e7aead7af27be/src/main/java/de/siphalor/nbtcrafting/mixin/MixinItemStack.java#L35-L39

**To Reproduce**
use cardinal components.
**Expected behavior**
Cardinal components'/vanilla minecraft's  correct item equality methods to be called, but they never do as you cancel them.

**Comment by Siphalor** [comment]
fixed in 2.0.3 - somehow this issue wasn't closed
