### ISSUE TITLE
[bug] Disconnection on world creation

### ISSUE THREAD

**Issue by ozokuz** [Siphalor/nbt-crafting#66]
**Version**
Minecraft: 1.16.5
Mod Version: 2.0.5

**Describe the bug**
When creating a world it disconnects

**To Reproduce**
No idea

**Expected behavior**
Should go into the world just like normal

**Log**
https://paste.ee/p/XAz2r#s=0&l=1340

**Comment by Siphalor** [comment]
According to Fourmisain this should be fixed in their pr :)
