### ISSUE TITLE
[bug] nbtcrafting:smithing recipes don't exist

### ISSUE THREAD

**Issue by ZombieNW** [Siphalor/nbt-crafting#67]
**Version**
1.16.4/5
**Describe the bug**
When a recipe with the type nbtcrafting:smithing is added to the datapack, it kicks everyone and says "unknown serialiser nbtcrafting:smithing"

**To Reproduce**
1. Use this json or craft something.
```
{
    "type": "nbtcrafting:smithing",
    "base": {
        "item": "minecraft:diamond_chestplate"
    },
    "addition": {
        "item": "minecraft:blue_dye",
		"data": {
			"CustomModelData":2
		}
    },
    "result": {
        "item": "minecraft:leather_chestplate",
		"data":{
			"$": "$ base",
			"display": {
				"Name": "{\"text\":\"Fancy Chestplate\",\"italic\":false}",
				"color": 4194411
			},
			"AttributeModifiers": [{"AttributeName":"generic.armor","Name":"generic.armor","Amount":9,"Operation":0,"UUID":[1996973360,-498333249,-2945680755,1617878268,"nbtcrafting:array_type=i"],"Slot":"chest"},{"AttributeName":"generic.armor_toughness","Name":"generic.armor_toughness","Amount":4,"Operation":0,"UUID":[1996973360,-498643249,-2945680755,1617878269,"nbtcrafting:array_type=i"],"Slot":"chest"}]
		}
    }
}
```
2. Bug appears

**Expected behavior**
I expected the recipe to work as depicted, using a special material you could make a stronger chestplate and would upgrade from a diamond one with the nbt, like diamond to netherite.

**Log**
Nothing was logged to the console regarding this.

**Additional context**
My server is trying to create a netherite alternative called netherite, after getting the material we're trying to make it so you can use it to make an enderite chestplate from a diamond chestplate.

**Comment by Nathan22211** [comment]
nbt crafting doesn't have hardcoded recipe types, it works with modded and vanilla recipe types. you want vanilla smithing NBT crafting only adds it for brewing and the cauldron

**Comment by Siphalor** [comment]
> nbt crafting doesn't have hardcoded recipe types, it works with modded and vanilla recipe types. you want vanilla smithing NBT crafting only adds it for brewing and the cauldron

Not sure if I understand you correctly but I think you're wrong.
The `nbtcrafting:smithing` recipe type exists as the Vanilla recipe already does NBT manipulation on its own (also for legacy reasons).
This issue is existing and easy to reproduce. I'm working on fixing it :)

**Comment by Decrepitdoors** [comment]
I'm having an issue with smithing recipes on my server, I didn't want to open a new bug report as I found this one similar to mine. 
Here's my recipe:
```
{
    "type": "minecraft:smithing",
    "base": {
        "item": "minecraft:snowball",
		"data":{
			"shuriken": "wood"
		}
    },
    "addition": {
        "item": "minecraft:iron_ingot"
	},
    "result": {
        "item": "minecraft:snowball",
		"data":{
			"shuriken": "iron",
			"CustomModelData": 420694,
			"display":{
				"Name": "{\"text\":\"Iron Shuriken\"}"
			}
		}
    }
}
```

I have tried both minecraft:smithing and nbtcrafting:smithing, with different results, nbtcrafting gives me the "Iron Shuriken" without an item in the second slot, minecraft doesn't change any of the nbt data and just gives me a "Wooden Shuriken"

I tried using the require in nbtcrafting but the recipe wouldn't load as it couldn't find an item or tag.
