### ISSUE TITLE
[bug] Client sync issue where NBT tags are not immediately copied to a remainder for duplicate recipe ingredients

### ISSUE THREAD

**Issue by sleepy-evelyn** [Siphalor/nbt-crafting#71]
**Version**
Minecraft version 1.16.5, 
NBT Crafting version 2.0.6+1.16.4

Quick heads up, works fine on a normal singleplayer world but not on a dedicated server indicating it's a client sync issue. Also could be related to #47 but the 2 workaround suggested don't seem to work

**Describe the bug**
Although the NBT data is copied to the remainder item left in the crafting grid it isn't displayed to the user on the client on a dedicated server until the user moves out of the crafting grid

**To Reproduce**
1) Create an item recipe that passes NBT data onto the remainder from another item
2) Hover over the item in the crafting grid that is left after the recipe is completed (the remainder) and the output crafted item is taken. The NBT data shouldn't be copied
3) Move the item from the crafting grid into your inventory. The NBT data should now update on the client for the item

**Expected behavior**
The NBT data should be immediately visible on the remainder from the client

**Log**
No log, instead just a recipe.
```json
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    {
      "item": "territorial:key",
      "data":{
        "deny": {
          "display": {
            "Name": ""
          }
        }
      }
    },
    {
      "item": "territorial:key",
      "remainder": {
        "item": "territorial:key",
        "data": {
          "$": "$ i1"
        }
      },
      "data": {
        "require": {
          "display": {
            "Name": ""
          }
        }
      }
    }
  ],
  "result":
  {
    "item": "territorial:key",
    "data": {
      "$": "$ i1"
    }
  }
}
```
Idea is nbt data is copied from one key to another by placing 1 blank key with no custom NBT data and one key with NBT data included such as the keys name and tooltip

Also tried with the ingredients reversed and this works on singleplayer immediately syncing but not on a dedicated server

**Comment by Siphalor** [comment]
I can't seem to be able to reproduce this.
Was the mod installed on the client side when this bug occurred?

**Comment by sleepy-evelyn** [comment]
I think so yes. The recipe was available to craft when opening in single player and I had no sync issues there. Only happens when crafting on a dedicated server and only if it's the same item
Also running in a development environment so the nbt-crafting dependency should be loaded on both the server and client.

If you need a way to reproduce the bug is still present in the following mod: https://github.com/Archydra-Studios/Territorial-Base
