### ISSUE TITLE
[bug] Brewing Stand GUI Acting Strange

### ISSUE THREAD

**Issue by ZombieNW** [Siphalor/nbt-crafting#75]
**Version**
1.16.5, 2.0.12
**Describe the bug**
Strange GUI behavior occurring while trying to use a brewing stand. Behavior like items glitching in and out of your inventory or not going in the right place, or when items are in the correct place it does not start brewing.

**To Reproduce**
1. Try to brew potions in a brewing stand while using the mod on a server
2. bug appears

**Expected behavior**
Items correctly go in to the slot and potions brew.

**Log**
N/A

**Additional context**
We have no brewing stand recipes, we are just trying to make vanilla potions.

**Comment by Siphalor** [comment]
Thanks for reporting :)
Fixed in 2.0.13
