### ISSUE TITLE
make the data tag able to take just the entire NBT data instead of separating it

### ISSUE THREAD

**Issue by Nathan22211** [Siphalor/nbt-crafting#8]
basically instead of having to do

`"item": "minecraft:diamond_axe",
		"data": {
			"display": {
				"Name": "{\"text\":\"Battle Axe\"}"
			},
			"Enchantments": [
				{
					"id": "minecraft:sharpness",
					"lvl": 10
				}
			]
		}
	}`
it could be reduced to `"item: "minecraft:diamond_axe"
                                                   "data": "{display:{Name:"{\"text\":\"battle axe\"}"},Enchantments:[{id:"minecraft:sharpness",lvl:5}]}"`

it makes recipes for some datapack makers easier considering the NBT often needs to be very specific

**Comment by Siphalor** [comment]
Should be fixed.
If neither `deny` nor `require` is given the object should now e interpreted as raw data.

**Comment by Siphalor** [comment]
Ok lol, I completely misunderstood you.
Nbt as strings if that's what you're looking for was once a thing but it has been discontinued since it's really messy with all that string escaping that needs to be done.

I'm not sure whether I'll reintroduce this at some point.

**Comment by Nathan22211** [comment]
i think json5 doesn't need string escaping

**Comment by Siphalor** [comment]
I guess I fixed that already a while ago 🤔 
@Nathan22211 Json5 or Hjson would be nice but would be a lot of work and would break vanilla compatibility.

Sorry for the long pause in development :) I can't guarantee that it'll become better though. ^^
