### ISSUE TITLE
[bug] Anvil displays recipe output but can't take the item

### ISSUE THREAD

**Issue by Decrepitdoors** [Siphalor/nbt-crafting#81]
**Version**
Minecraft 1.17 version 2.0.19
**Describe the bug**
I created some anvil recipes to let players dye their elytra, the textured elytra show up in the anvil but I can't take it out.

**To Reproduce**
1. Use this json or craft something.

```
{
    "type": "nbtcrafting:anvil",
    "base": {
        "item": "minecraft:elytra"
    },
    "ingredient": {
        "item": "minecraft:black_dye"
    },
    "result": {
        "item": "minecraft:elytra",
		"data":{
			"elytra":"black"
		}
    }
}
```

2. Bug appears

**Expected behavior**
Anvil recipe would let me take the item.

**Additional context**
I am running with a few other mods but nothing that changes crafting mechanics at all
Crafting recipes still work for my custom items

**Comment by Siphalor** [comment]
Apparently Vanilla has a check that cancels the interaction if the required xp level is 0 or less.

I'm gonna circumvent this check in the hope that this doesn't cause any other issues.
Please let me know if you have an idea on what Vanilla might be checking this for.

**Comment by Decrepitdoors** [comment]
That makes sense, I didn't try it with any levels as the cost, I don't mind adding a level to dye them if it fixes this without you having to go around anything

**Comment by Siphalor** [comment]
Well I consider this as a bug since the `levels` property is optional and shouldn't cause any issues if left out.

Also, giving the player levels by crafting might be an interesting mechanic too :)
