### ISSUE TITLE
[1.17.1 Bug] NBTCrafting causing issues with REI

### ISSUE THREAD

**Issue by itsdinkd** [Siphalor/nbt-crafting#83]
nevermind turned out to be McDOOM's fault for not implementing correctly. Once removing the NBTCrafting dependency that was never called upon REI worked again.

**Comment by frikinjay** [comment]
I talked to MC Doom mod's dev and I was told NBTcrafting is needed to craft a book. Are you sure about it not being used?

**Comment by YoureNotSmarthuh** [comment]
He fixed it in his most recent version released two days ago, (NBTCrafting) actually being used for the recipe. As you can see his mod still conflicts with NBTcrafting yet if you use NBTCrafting anywhere else the problem doesn't occur.

**Comment by itsdinkd** [comment]
That's funny because if you look at his code you will see that he is not using NBTCrafting. He is just throwing it in Gradle and creating a .json recipe for his book, which will not work. https://mcwiki.siphalor.de/nbt-crafting/v2/#updating/ 

Also, NBTCrafting is **not needed** to craft a patchouli book. I have 180+ Mods and no other author is using NBTCrafting for their patchouli book recipes but McDoom.  Industrial Revolution does not use NBTCrafting but uses patchouli for their book, https://github.com/GabrielOlvH/Industrial-Revolution/blob/master/src/main/resources/data/indrev/recipes/shapeless/guide_book.json

He is blaming NBTCrafting because he doesn't want to actually fix any code on his part that conflicts with it because as he said himself "He mods for himself" and he doesn't use REI nor cares about it.

**Comment by AzureDoom** [comment]
> That's funny because if you look at his code you will see that he is not using NBTCrafting. He is just throwing it in Gradle and creating a .json recipe for his book, which will not work. https://mcwiki.siphalor.de/nbt-crafting/v2/#updating/
> 
> Also, NBTCrafting is **not needed** to craft a patchouli book. I have 180+ Mods and no other author is using NBTCrafting for their patchouli book recipes but McDoom. Industrial Revolution does not use NBTCrafting but uses patchouli for their book, https://github.com/GabrielOlvH/Industrial-Revolution/blob/master/src/main/resources/data/indrev/recipes/shapeless/guide_book.json
> 
> He is blaming NBTCrafting because he doesn't want to actually fix any code on his part that conflicts with it because as he said himself "He mods for himself" and he doesn't use REI nor cares about it.

that mod uses it's own custom book item, making patchouli a hard requirement where I leave it as an optional depend. https://mcwiki.siphalor.de/nbt-crafting/v2/#recipe-parts/results/ but please tell me how I'm using this wrong again. Next time take the stick out of your ass and admit your wrong fuck face.

**Comment by AzureDoom** [comment]
This all ended up being moot in regards to the MCDoom Patchouli book thanks to a silent change that Patchouli **never publicly stated** <https://github.com/VazkiiMods/Patchouli/blob/1.17-fabric/src/main/java/vazkii/patchouli/common/item/PatchouliItems.java#L21>, they finally added a crafting system to 1.17 for book recipes. Note this change was never listed in their upgrading doc nor their "change log". I just happened upon it when I was digging around it's code for setting my book in a custom creative tab. williewillus themselves stated they forgot about the feature.
![image](https://user-images.githubusercontent.com/7415711/132165187-16e4d46f-0c78-4667-8d17-f2b98d4ced5b.png)

**Comment by itsdinkd** [comment]
Woooooah he actually fixed it! MAde him look on how to properly use Patchouli instead of blaming other mods.

"Next time take the stick out of your ass and admit your wrong fuck face."

"stay away from my discord" (as you joined my discord with a fake, new account to say that as you tried to "ban" me from using your open-source licensed mod that I fixed to work with REI)

You sure are a hyprocite lmfao. What am I supposed to be wrong about? Reporting issues to you and you being too ego driven to even take a look instead of blaming other mods that you used? Your mod having major conflicts? You not running basic quality assurance before pushing live for thousands to download and your mod ending up crashing their clients? You should thank me, otherwise you still would not have fixed your patchouli recipe.

As you just showed further how egotistical you are for your incompetence, you should take your own advice and apologize to me. WIthout me, you would still be telling others to **my crash report** that you told me to post here.

**Comment by itsdinkd** [comment]
By the way, you were using it wrong by not including the "DATA" property which the NBT tag was supposed to be in. All you had under result was item, nbt:[]  :) 

PS:  I never initially said you used NBTCrafting wrong, I said you were never using it at all. Now I am saying you used it wrong. It's okay to make bad code, but don't get mad when other people try to report issues to you. cocky bastard. Looks like you are self-projecting a little bit. 

![image](https://user-images.githubusercontent.com/35115304/132169906-754e3599-5de1-43d5-9f9e-76519bb64e97.png)
