### ISSUE TITLE
Unable to join to (vanilla) server

### ISSUE THREAD

**Issue by Felix14-v2** [Siphalor/nbt-crafting#85]
**Version**
Minecraft: Server/Client 1.17.1
NBT Crafting 2.0.22

**Description**
[[Demo]](https://youtu.be/BfmmiqL-nLc)

**To Reproduce**
1. Install only Fabric 0.11.6 and NBT Crafting
2. Run vanilla server
3. Try to join
4. Get disconnect

**Log**
Absolutely normal.

**Comment by Siphalor** [comment]
Well, that was never meant to work.

Nbt Crafting is a mod that is designed to run server side only and provides some visual additions and fixes for the client.

Therefor:

Client: Optional
Server: Required

If you want to join a vanilla-ish server then you'll have to remove Nbt Crafting on the client end.

**Comment by Felix14-v2** [comment]
Ok...
