### ISSUE TITLE
[bug] It is impossible to rename stacks of items

### ISSUE THREAD

**Issue by Milhax** [Siphalor/nbt-crafting#86]
**Version**
Using Minecraft version 1.17.1 and nbtcrafting@2.1.0+mc1.17.1
**Describe the bug**
While only having nbtcrafting loaded it is impossible to rename a stack of items even though a level of experience is used

**To Reproduce**
1 : go into a singleplayer world
2 : get an Anvil and a stack of any item
3 : try to rename it

**Expected behavior**
The entire stack gets renamed and a level is used

**Log**
nothing in the log

**Additional context**
I am doing this text in a singleplayer world

**Comment by kevinbevers** [comment]
I also experienced this today, was about to report it but seems it's already mentioned.

+1

edit: in 1.18.1
