### ISSUE TITLE
[bug] Stack renaming duplication bug. only taking 1 item.

### ISSUE THREAD

**Issue by kevinbevers** [Siphalor/nbt-crafting#88]
**Version**
1.18
**Describe the bug**
Renaming a stack of items gives back the full item stack but only takes one away. creating a dupe.

**To Reproduce**
1. Rename a stack in an anvil
2. Bug appears

**Expected behavior**
The stack to just be renamed and using up the full stack when doing so. instead of only using up 1 item and giving back 64 renamed ones

Issue was maybe created during this commit: https://github.com/Siphalor/nbt-crafting/commit/12d177665379d72648d14f2d1072970902c830a1

**Comment by Greg-J** [comment]
@Siphalor, this is a server-breaking bug. Can we get a hotfix of the current build with this fix in it by chance? This is a bad one and _completely_ breaks server economy.

**Comment by Siphalor** [comment]
Oh shit.

I fixed this last year but due to a lot of stuff going on I forgot to push a release out.
Version 2.1.1 is coming out right now.

Thanks for reminding me!

**Comment by Greg-J** [comment]
You rock. Cheers.
