### ISSUE TITLE
Inheriting NBT

### ISSUE THREAD

**Issue by Eleectroo** [Siphalor/nbt-crafting#9]
Hey! I don't know if it's possible, but can you make it so, that when you craft an item and the input item id and the output id are the same, it doesn't make a new item, it just adds the nbt to the others? For example when you wan't to dye a tool that is damaged, it won't give you a new tool, therefore cheating you extra durability.

**Comment by Siphalor** [comment]
Quick update: I'm working on this long planned feature but it takes some time and some breaks to squish bugs and get this thing ready. 
Stay tuned.
